import { z } from "zod";

export const umkmProfileSchema = z.object({
  id_data_badan_usaha: z.string().min(1, "ID data badan usaha wajib diisi"),
  nik_pengusaha: z.string().min(1, "NIK pengusaha wajib diisi"),
  nama_pengusaha: z.string().min(1, "Nama pengusaha wajib diisi"),
  nib: z.string().nullable(),
  jenis_kelamin: z.enum(["L", "P"]),
  is_disabilitas: z.boolean(),
  tanggal_lahir: z.string().nullable(),
  prov_pengusaha: z.string().min(1, "Provinsi pengusaha wajib diisi"),
  kab_pengusaha: z.string().min(1, "Kabupaten pengusaha wajib diisi"),
  kec_pengusaha: z.string().min(1, "Kecamatan pengusaha wajib diisi"),
  kel_pengusaha: z.string().min(1, "Kelurahan pengusaha wajib diisi"),
  alamat_pengusaha: z.string().min(1, "Alamat pengusaha wajib diisi"),
  rt_pengusaha: z.string().nullable(),
  rw_pengusaha: z.string().nullable(),
  kontak_hp: z.string().min(1, "Kontak HP wajib diisi"),
  pendidikan_formal: z.string().nullable(),
  nama_usaha: z.string().min(1, "Nama usaha wajib diisi"),
  kegiatan_utama: z.string().nullable(),
  produk_utama: z.string().nullable(),
  kategori_kbli: z.string().nullable(),
  kode_kbli: z.string().nullable(),
  status_badan_usaha: z.string().nullable(),
  modal_pendirian: z.number().nullable(),
  bulan_mulai_operasi: z.number().nullable(),
  tahun_mulai_operasi: z.number().nullable(),
  prov_usaha: z.string().min(1, "Provinsi usaha wajib diisi"),
  kab_usaha: z.string().min(1, "Kabupaten usaha wajib diisi"),
  kec_usaha: z.string().min(1, "Kecamatan usaha wajib diisi"),
  kel_usaha: z.string().min(1, "Kelurahan usaha wajib diisi"),
  alamat_usaha: z.string().min(1, "Alamat usaha wajib diisi"),
  rt_usaha: z.string().nullable(),
  rw_usaha: z.string().nullable(),
  foto_usaha: z.string().nullable(),
  alamat_latitude: z.number().nullable(),
  alamat_longitude: z.number().nullable(),
  tk_dibayar_laki: z.number(),
  tk_dibayar_perempuan: z.number(),
  tk_dibayar_disabil_laki: z.number(),
  tk_dibayar_disabil_perempuan: z.number(),
  tk_not_dibayar_laki: z.number(),
  tk_not_dibayar_perempuan: z.number(),
  tk_not_dibayar_disabil_laki: z.number(),
  tk_not_dibayar_disabil_perempuan: z.number(),
  skala_usaha: z.string().nullable(),
  omzet_tahunan: z.number().nullable(),
  asset: z.number().nullable(),
});
